require('mason-tool-installer').setup {
  ensure_installed = {
    "alejandra",
    "cbfmt",
    "clang-format",
    "doctoc",
    "emmet-language-server",
    "emmylua_ls",
    "eslint-lsp",
    "gopls",
    "htmx-lsp",
    "jdtls",
    "json-lsp",
    "ltex-ls",
    "lua-language-server",
    "nil",
    "prettierd",
    "pylint",
    "rustywind",
    "tailwindcss-language-server",
    "templ",
    "typescript-language-server",
    "zls"
  },
  auto_update = true,
  run_on_start = true,
  start_delay = 5000,
  debounce_hours = 1,
  integrations = {
    ['mason-lspconfig'] = true,
    ['mason-null-ls'] = false,
    ['mason-nvim-dap'] = false,
  },
}
