require('mason-tool-installer').setup {
  ensure_installed = {
    "jdtls",
    "alejandra",
    "ast-grep",
    "ast_grep",
    "bash-language-server",
    "bashls",
    "biome",
    "cbfmt",
    "cfn-lint",
    "clang-format",
    "dcm",
    "doctoc",
    "emmet-language-server",
    "emmet_language_server",
    "emmylua_ls",
    "glint",
    "gopls",
    "json-lsp",
    "ltex-ls",
    "ltex",
    "lua-language-server",
    "lua_ls",
    "nil",
    "nil_ls",
    "prettier",
    "prettierd",
    "pylint",
    "quick-lint-js",
    "quick_lint_js",
    "rustywind",
    "tailwindcss-language-server",
    "tailwindcss",
    "typescript-language-server",
    "ts_ls",
    "zls",
  },
  auto_update = false,
  run_on_start = true,
  start_delay = 3000, -- 3 second delay
  debounce_hours = 1, -- at least 1 hours between attempts to install/update
  integrations = {
    ['mason-lspconfig'] = true,
    ['mason-null-ls'] = false,
    ['mason-nvim-dap'] = false,
  },
}
